# Generated by Django 3.1.6 on 2021-02-04 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=550)),
                ('icon', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('logo', models.FileField(blank=True, default=None, upload_to='')),
                ('slug', models.CharField(default=' ', max_length=550, null=True)),
                ('summary', models.TextField(blank=True)),
                ('sole_partner', models.CharField(default=' ', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Builders',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=1100)),
                ('slug', models.CharField(default=' ', max_length=1100, null=True)),
                ('res_com', models.CharField(default='Residential', max_length=1100, null=True)),
                ('location', models.CharField(default=' ', max_length=1100)),
                ('summary', models.CharField(default=' ', max_length=1100, null=True)),
                ('project_area', models.CharField(default=' ', max_length=1100)),
                ('no_of_units', models.CharField(default=' ', max_length=550)),
                ('no_of_floors', models.CharField(default=' ', max_length=550)),
                ('open_area', models.CharField(default=' ', max_length=550)),
                ('no_of_tower', models.CharField(default=' ', max_length=550)),
                ('no_of_block', models.CharField(default=' ', max_length=550)),
                ('prop_type', models.CharField(default=None, max_length=550)),
                ('banner_image', models.FileField(blank=True, default=' ', upload_to='')),
                ('base_price', models.CharField(default=None, max_length=550, null=True)),
                ('status', models.CharField(default=' ', max_length=550, null=True)),
                ('sq_feet_price', models.CharField(default=None, max_length=550, null=True)),
                ('possession_date', models.CharField(default=None, max_length=550, null=True)),
                ('overview', models.TextField(default=None, max_length=10000)),
                ('video', models.CharField(default=' ', max_length=10000)),
                ('google_map', models.CharField(default=' ', max_length=10000)),
                ('rera', models.TextField(default=None, max_length=1000)),
                ('master_plan', models.FileField(blank=True, default=' ', upload_to='')),
                ('construction_video', models.FileField(blank=True, default=' ', upload_to='')),
                ('home_banner_display', models.CharField(default='No', max_length=550, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(to='shi_app.Amenities')),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shi_app.builder')),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
    ]
