# Generated by Django 3.1.6 on 2021-02-08 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropSiteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(default=' ', max_length=550)),
                ('block', models.CharField(max_length=550, null=True)),
                ('phase', models.CharField(default=' ', max_length=550)),
                ('inclusion', models.TextField(default=' ', max_length=1000)),
                ('builtup_area_sqft', models.FloatField(default=None, null=True)),
                ('carpet_area_sqft', models.FloatField(default=None, null=True)),
                ('balcony_area', models.FloatField(default=None, null=True)),
                ('rate_sqft', models.FloatField(default=None, null=True)),
                ('agreement_value', models.FloatField(default=' ', null=True)),
                ('floor_plan', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shi_app.property')),
            ],
            options={
                'verbose_name_plural': 'Property Site Details',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=550)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shi_app.property')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=550)),
                ('attached_file', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shi_app.property')),
            ],
            options={
                'verbose_name_plural': 'Downloads',
            },
        ),
    ]
